# Linear equations

In [1]:
import numpy as np

A = np.array(([2, -1],
              [-2, 1],
              [-1, 2]))
B = np.array(([4, -3],
              [3, 5]))

print(A)
print(B)

A@B

[[ 2 -1]
 [-2  1]
 [-1  2]]
[[ 4 -3]
 [ 3  5]]


array([[  5, -11],
       [ -5,  11],
       [  2,  13]])

In [4]:
A = np.array(([2, 5],
              [1, 3]))

print("Inverse a\n", np.linalg.inv(A))

np.linalg.inv(A)@A

Inverse a
 [[ 3. -5.]
 [-1.  2.]]


array([[1., 0.],
       [0., 1.]])

In [3]:
print(A.transpose())


array([[2, 1],
       [5, 3]])